module.exports = require('coa').Cmd()
  .name(process.argv[1])
    .title('Yadisk. ololo blyat.')
    .helpful()
    .opt()
        .name('version') .title('Version')
        .short('v').long('version')
        .flag()
        .only()
        .act(function() { return JSON.parse(FS.readFileSync(PATH.resolve(__dirname, '..', 'package.json'))).version })
        .end()
    .cmd().name('test').apply(require('./commands/test')).end();
